services:
  mrt-manifest-gen:
    container_name: mrt-manifest-gen
    image: ${ECR_REGISTRY}/mrt-manifest-gen
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AWS_PROFILE: ${AWS_PROFILE:-default}
      AWS_REGION: ${AWS_REGION:-us-west-2}
      
      PROJECT_NAME: ${PROJECT_NAME:-not-applicable}

      # Allowed values: s3api, httpsapi, inventoryfile, inventoryurl
      MANIFEST_MODE: ${MANIFEST_MODE:-s3api}
      # In s3api mode, MANIFEST_BUCKET is the name of the bucket
      MANIFEST_BUCKET: ${MANIFEST_BUCKET:-merritt-ingest-workspace-${PROJECT_NAME}}

      # MANIFEST_MODE: httpsapi
      # In httpsapi mode, MANIFEST_BUCKET is the base URL to reach the bucket
      # MANIFEST_BUCKET: ${MANIFEST_BUCKET:-https://merritt-ingest-workspace-${PROJECT_NAME}.s3.${AWS_REGION}.amazonaws.com}

      # MANIFEST_MODE: inventoryfile
      # In inventoryfile mode, MANIFEST_FILE is the path to the inventory file
      # MANIFEST_FILE: ...csv

      # MANIFEST_MODE: inventoryurl
      # In inventoryurl mode, MANIFEST_URL is the URL to reach the inventory file
      # MANIFEST_URL: https://...csv

      # This will trigger only a subset of paths to be (re)loaded
      MANIFEST_PREFIX: ${MANIFEST_PREFIX:-}

      # Cache Mode: S3 or local
      CACHE_MODE: ${CACHE_MODE:-S3}
      CACHE_BUCKET: ${CACHE_BUCKET:-merritt-ingest-workspace-cache}
      # CACHE_FOLDER: /tmp/cache

    volumes:      
      - ~/.aws:/root/.aws:ro
      #- ./inventory:/tmp/inventory
    ports:
      - "9292:9292"
    entrypoint:
      - "bundle"
      - "exec"
      - "puma"
      - "app/config_mrt.ru"
